name: Deploy Site

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy to host branch
        run: |
          git fetch origin

          git switch --orphan host-temp

          find . -mindepth 1 -maxdepth 1 \
            ! -name '.git' \
            -exec rm -rf {} +

          git checkout origin/main -- .

          rm -rf .github

          git add .

          git commit -m "Deploy site" || echo "No changes"

          git branch -D host 2>/dev/null || true
          git branch -m host

          git push origin host --force
